permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "juice."
  description: A small business that sells juice.
  font_url: "https://fonts.googleapis.com/css2?family=Archivo:wght@400;600&family=Zilla+Slab:ital,wght@0,400;0,600;1,400&display=swap"
  layouts:
    default: |
      The default layout should be used for almost every page, it includes the website's primary header & footer.
    products: |
      The products layout should be used for the products page.

  colors:
    background: "--color-primary"
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-secondary"

  rationales:
    typefaces.primary: |
      Zilla Slab was selected because it works well on screens. It will be used for all body copy.
    typefaces.secondary: |
      Archivo was selected because it's an elegant sans-serif. It will be used in all headings, buttons, banners, etc.
    colors.primary: |
      The primary colours are more neutral and should be used for backgrounds.
    colors.secondary: |
      The secondary colours represent nature. They should be used for text and forground.
