permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Crystals"
  description: A small business that sells crystals.
  font_url: "https://fonts.googleapis.com/css?family=Merriweather:300,300i,400,400i,700|Raleway:300,400,600,700&display=swap"
  colors:
    background:
    accent: "--color-accent"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.primary: |
      Merriweather was selected because it works well on screens. It will be used for all body copy.
    typefaces.secondary: |
      Raleway was selected because it's an elegant sans-serif. It will be used in all headings, buttons, banners, etc.
    colors.primary: |
      The primary colours represent crystals and all their many colours. They should be used for text and forground.
    colors.secondary: |
      The secondary colours are more neutral and should be used for backgrounds.
