title: "Forms"
description: |
  Forms are created to allow customers to make accounts. The information captured is for the purpose of charging customers and shipping items to them.
patterns:
  email-field:
    title: "Email Field"
    description: The email is necessary to send electronic proof of their purchase as well as promotions.
    width: 20em

  address-field:
    title: "Address Field"
    description: The address is necessary for shipping their purchases.
    width: 20em

  dropdown:
    title: "Dropdown Field"
    description: The dropdown is used to choose their province.
    width: 20em

    phone-number-field:
      title: "Phone Number Field"
      description: The phone number is necessary as a back-up for contacting the customer in regards to their purchases being shipped.
      width: 20em
