title: "Navigation"
description: |
  Navigation is to help direct you from one piece of information to another.

patterns:
  back:
    title: "Previous Page"
    description: |
      The previous page navigation is only to be used in the **top left** corner of all product information cards, checkout pages, payment method,
    width: "12em"
